from ophyd import (EpicsSignal, EpicsSignalRO)

from .. import (RecordBase, _register_record_type,
                FieldComponent as Cpt)


@_register_record_type('calcout')
class CalcoutRecord(RecordBase):
    alarm_status = Cpt(EpicsSignalRO, '.STAT')
    calc_valid = Cpt(EpicsSignal, '.CLCV')
    inpa_pv_status = Cpt(EpicsSignalRO, '.INAV')
    inpb_pv_status = Cpt(EpicsSignalRO, '.INBV')
    inpc_pv_status = Cpt(EpicsSignalRO, '.INCV')
    inpd_pv_status = Cpt(EpicsSignalRO, '.INDV')
    inpe_pv_status = Cpt(EpicsSignalRO, '.INEV')
    inpf_pv_status = Cpt(EpicsSignalRO, '.INFV')
    inpg_pv_status = Cpt(EpicsSignalRO, '.INGV')
    inph_pv_status = Cpt(EpicsSignalRO, '.INHV')
    inpi_pv_status = Cpt(EpicsSignalRO, '.INIV')
    inpj_pv_status = Cpt(EpicsSignalRO, '.INJV')
    inpk_pv_status = Cpt(EpicsSignalRO, '.INKV')
    inpl_pv_status = Cpt(EpicsSignalRO, '.INLV')
    last_val_monitored = Cpt(EpicsSignalRO, '.MLST')
    last_value_alarmed = Cpt(EpicsSignalRO, '.LALM')
    last_value_archived = Cpt(EpicsSignalRO, '.ALST')
    ocal_valid = Cpt(EpicsSignal, '.OCLV')
    out_pv_status = Cpt(EpicsSignalRO, '.OUTV')
    output_delay_active = Cpt(EpicsSignalRO, '.DLYA')
    output_value = Cpt(EpicsSignal, '.OVAL')
    prev_value_of_a = Cpt(EpicsSignalRO, '.LA')
    prev_value_of_b = Cpt(EpicsSignalRO, '.LB')
    prev_value_of_c = Cpt(EpicsSignalRO, '.LC')
    prev_value_of_d = Cpt(EpicsSignalRO, '.LD')
    prev_value_of_e = Cpt(EpicsSignalRO, '.LE')
    prev_value_of_f = Cpt(EpicsSignalRO, '.LF')
    prev_value_of_g = Cpt(EpicsSignalRO, '.LG')
    prev_value_of_h = Cpt(EpicsSignalRO, '.LH')
    prev_value_of_i = Cpt(EpicsSignalRO, '.LI')
    prev_value_of_j = Cpt(EpicsSignalRO, '.LJ')
    prev_value_of_k = Cpt(EpicsSignalRO, '.LK')
    prev_value_of_l = Cpt(EpicsSignalRO, '.LL')
    prev_value_of_oval = Cpt(EpicsSignal, '.POVL')
    previous_value = Cpt(EpicsSignal, '.PVAL')
    value_of_input_a = Cpt(EpicsSignal, '.A')
    value_of_input_b = Cpt(EpicsSignal, '.B')
    value_of_input_c = Cpt(EpicsSignal, '.C')
    value_of_input_d = Cpt(EpicsSignal, '.D')
    value_of_input_e = Cpt(EpicsSignal, '.E')
    value_of_input_f = Cpt(EpicsSignal, '.F')
    value_of_input_g = Cpt(EpicsSignal, '.G')
    value_of_input_h = Cpt(EpicsSignal, '.H')
    value_of_input_i = Cpt(EpicsSignal, '.I')
    value_of_input_j = Cpt(EpicsSignal, '.J')
    value_of_input_k = Cpt(EpicsSignal, '.K')
    value_of_input_l = Cpt(EpicsSignal, '.L')

    # - alarms
    alarm_deadband = Cpt(EpicsSignal, '.HYST')
    high_alarm_limit = Cpt(EpicsSignal, '.HIGH')
    high_severity = Cpt(EpicsSignal, '.HSV')
    hihi_alarm_limit = Cpt(EpicsSignal, '.HIHI')
    hihi_severity = Cpt(EpicsSignal, '.HHSV')
    lolo_alarm_limit = Cpt(EpicsSignal, '.LOLO')
    lolo_severity = Cpt(EpicsSignal, '.LLSV')
    low_alarm_limit = Cpt(EpicsSignal, '.LOW')
    low_severity = Cpt(EpicsSignal, '.LSV')
    output_execute_delay = Cpt(EpicsSignal, '.ODLY')

    # - calc
    calculation = Cpt(EpicsSignal, '.CALC$')
    input_a = Cpt(EpicsSignal, '.INPA$')
    input_b = Cpt(EpicsSignal, '.INPB$')
    input_c = Cpt(EpicsSignal, '.INPC$')
    input_d = Cpt(EpicsSignal, '.INPD$')
    input_e = Cpt(EpicsSignal, '.INPE$')
    input_f = Cpt(EpicsSignal, '.INPF$')
    input_g = Cpt(EpicsSignal, '.INPG$')
    input_h = Cpt(EpicsSignal, '.INPH$')
    input_i = Cpt(EpicsSignal, '.INPI$')
    input_j = Cpt(EpicsSignal, '.INPJ$')
    input_k = Cpt(EpicsSignal, '.INPK$')
    input_l = Cpt(EpicsSignal, '.INPL$')
    output_calculation = Cpt(EpicsSignal, '.OCAL$')
    output_data_opt = Cpt(EpicsSignal, '.DOPT')
    output_execute_opt = Cpt(EpicsSignal, '.OOPT')

    # - clock
    event_to_issue = Cpt(EpicsSignal, '.OEVT')

    # - display
    archive_deadband = Cpt(EpicsSignal, '.ADEL')
    display_precision = Cpt(EpicsSignal, '.PREC')
    high_operating_rng = Cpt(EpicsSignal, '.HOPR')
    low_operating_range = Cpt(EpicsSignal, '.LOPR')
    monitor_deadband = Cpt(EpicsSignal, '.MDEL')
    units_name = Cpt(EpicsSignal, '.EGU$')

    # - output
    invalid_output_action = Cpt(EpicsSignal, '.IVOA')
    invalid_output_value = Cpt(EpicsSignal, '.IVOV')
    output_specification = Cpt(EpicsSignal, '.OUT$')
