from ophyd import (EpicsSignal, EpicsSignalRO, Component as Cpt)

from .. import (RecordBase, _register_record_type)


@_register_record_type('mbbi')
class MbbiRecord(RecordBase):
    _rtyp = 'mbbi'
    alarm_status = Cpt(EpicsSignalRO, '.STAT')
    hardware_mask = Cpt(EpicsSignalRO, '.MASK')
    last_value_alarmed = Cpt(EpicsSignalRO, '.LALM')
    last_value_monitored = Cpt(EpicsSignalRO, '.MLST')
    prev_raw_value = Cpt(EpicsSignalRO, '.ORAW')
    raw_value = Cpt(EpicsSignal, '.RVAL')
    simulation_mode = Cpt(EpicsSignal, '.SIMM')
    simulation_value = Cpt(EpicsSignal, '.SVAL')
    states_defined = Cpt(EpicsSignalRO, '.SDEF')

    # - bits1
    five_string = Cpt(EpicsSignal, '.FVST')
    five_value = Cpt(EpicsSignal, '.FVVL')
    four_string = Cpt(EpicsSignal, '.FRST')
    four_value = Cpt(EpicsSignal, '.FRVL')
    one_string = Cpt(EpicsSignal, '.ONST')
    one_value = Cpt(EpicsSignal, '.ONVL')
    seven_string = Cpt(EpicsSignal, '.SVST')
    seven_value = Cpt(EpicsSignal, '.SVVL')
    six_string = Cpt(EpicsSignal, '.SXST')
    six_value = Cpt(EpicsSignal, '.SXVL')
    state_five_severity = Cpt(EpicsSignal, '.FVSV')
    state_four_severity = Cpt(EpicsSignal, '.FRSV')
    state_one_severity = Cpt(EpicsSignal, '.ONSV')
    state_seven_severity = Cpt(EpicsSignal, '.SVSV')
    state_six_severity = Cpt(EpicsSignal, '.SXSV')
    state_three_severity = Cpt(EpicsSignal, '.THSV')
    state_two_severity = Cpt(EpicsSignal, '.TWSV')
    state_zero_severity = Cpt(EpicsSignal, '.ZRSV')
    three_string = Cpt(EpicsSignal, '.THST')
    three_value = Cpt(EpicsSignal, '.THVL')
    two_string = Cpt(EpicsSignal, '.TWST')
    two_value = Cpt(EpicsSignal, '.TWVL')
    zero_string = Cpt(EpicsSignal, '.ZRST')
    zero_value = Cpt(EpicsSignal, '.ZRVL')

    # - bits2
    eight_string = Cpt(EpicsSignal, '.EIST')
    eight_value = Cpt(EpicsSignal, '.EIVL')
    eleven_string = Cpt(EpicsSignal, '.ELST')
    eleven_value = Cpt(EpicsSignal, '.ELVL')
    fifteen_string = Cpt(EpicsSignal, '.FFST')
    fifteen_value = Cpt(EpicsSignal, '.FFVL')
    fourteen_string = Cpt(EpicsSignal, '.FTST')
    fourteen_value = Cpt(EpicsSignal, '.FTVL')
    nine_string = Cpt(EpicsSignal, '.NIST')
    nine_value = Cpt(EpicsSignal, '.NIVL')
    state_eight_severity = Cpt(EpicsSignal, '.EISV')
    state_eleven_severity = Cpt(EpicsSignal, '.ELSV')
    state_fifteen_severity = Cpt(EpicsSignal, '.FFSV')
    state_fourteen_sevr = Cpt(EpicsSignal, '.FTSV')
    state_nine_severity = Cpt(EpicsSignal, '.NISV')
    state_ten_severity = Cpt(EpicsSignal, '.TESV')
    state_thirteen_sevr = Cpt(EpicsSignal, '.TTSV')
    state_twelve_severity = Cpt(EpicsSignal, '.TVSV')
    ten_string = Cpt(EpicsSignal, '.TEST')
    ten_value = Cpt(EpicsSignal, '.TEVL')
    thirteen_string = Cpt(EpicsSignal, '.TTST')
    thirteen_value = Cpt(EpicsSignal, '.TTVL')
    twelve_string = Cpt(EpicsSignal, '.TVST')
    twelve_value = Cpt(EpicsSignal, '.TVVL')

    # - mbb
    change_of_state_svr = Cpt(EpicsSignal, '.COSV')
    input_specification = Cpt(EpicsSignal, '.INP')
    number_of_bits = Cpt(EpicsSignalRO, '.NOBT')
    shift = Cpt(EpicsSignal, '.SHFT')
    sim_input_specifctn = Cpt(EpicsSignal, '.SIOL')
    sim_mode_location = Cpt(EpicsSignal, '.SIML')
    sim_mode_alarm_svrty = Cpt(EpicsSignal, '.SIMS')
    unknown_state_severity = Cpt(EpicsSignal, '.UNSV')
