from ophyd import (EpicsSignal, EpicsSignalRO, Component as Cpt)

from .. import (RecordBase, _register_record_type)


@_register_record_type('sel')
class SelRecord(RecordBase):
    _rtyp = 'sel'
    alarm_status = Cpt(EpicsSignalRO, '.STAT')
    index_value = Cpt(EpicsSignal, '.SELN')
    last_index_monitored = Cpt(EpicsSignalRO, '.NLST')
    last_val_monitored = Cpt(EpicsSignalRO, '.MLST')
    last_value_alarmed = Cpt(EpicsSignalRO, '.LALM')
    last_value_archived = Cpt(EpicsSignalRO, '.ALST')
    prev_value_of_a = Cpt(EpicsSignalRO, '.LA')
    prev_value_of_b = Cpt(EpicsSignalRO, '.LB')
    prev_value_of_c = Cpt(EpicsSignalRO, '.LC')
    prev_value_of_d = Cpt(EpicsSignalRO, '.LD')
    prev_value_of_e = Cpt(EpicsSignalRO, '.LE')
    prev_value_of_f = Cpt(EpicsSignalRO, '.LF')
    prev_value_of_g = Cpt(EpicsSignalRO, '.LG')
    prev_value_of_h = Cpt(EpicsSignalRO, '.LH')
    prev_value_of_i = Cpt(EpicsSignalRO, '.LI')
    prev_value_of_j = Cpt(EpicsSignalRO, '.LJ')
    prev_value_of_k = Cpt(EpicsSignalRO, '.LK')
    prev_value_of_l = Cpt(EpicsSignalRO, '.LL')
    value_of_input_a = Cpt(EpicsSignal, '.A')
    value_of_input_b = Cpt(EpicsSignal, '.B')
    value_of_input_c = Cpt(EpicsSignal, '.C')
    value_of_input_d = Cpt(EpicsSignal, '.D')
    value_of_input_e = Cpt(EpicsSignal, '.E')
    value_of_input_f = Cpt(EpicsSignal, '.F')
    value_of_input_g = Cpt(EpicsSignal, '.G')
    value_of_input_h = Cpt(EpicsSignal, '.H')
    value_of_input_i = Cpt(EpicsSignal, '.I')
    value_of_input_j = Cpt(EpicsSignal, '.J')
    value_of_input_k = Cpt(EpicsSignal, '.K')
    value_of_input_l = Cpt(EpicsSignal, '.L')

    # - alarms
    alarm_deadband = Cpt(EpicsSignal, '.HYST')
    high_alarm_limit = Cpt(EpicsSignal, '.HIGH')
    high_severity = Cpt(EpicsSignal, '.HSV')
    hihi_alarm_limit = Cpt(EpicsSignal, '.HIHI')
    hihi_severity = Cpt(EpicsSignal, '.HHSV')
    lolo_alarm_limit = Cpt(EpicsSignal, '.LOLO')
    lolo_severity = Cpt(EpicsSignal, '.LLSV')
    low_alarm_limit = Cpt(EpicsSignal, '.LOW')
    low_severity = Cpt(EpicsSignal, '.LSV')

    # - display
    archive_deadband = Cpt(EpicsSignal, '.ADEL')
    display_precision = Cpt(EpicsSignal, '.PREC')
    high_operating_rng = Cpt(EpicsSignal, '.HOPR')
    low_operating_range = Cpt(EpicsSignal, '.LOPR')
    monitor_deadband = Cpt(EpicsSignal, '.MDEL')
    units_name = Cpt(EpicsSignal, '.EGU')

    # - inputs
    index_value_location = Cpt(EpicsSignal, '.NVL')
    select_mechanism = Cpt(EpicsSignal, '.SELM')

    # - select
    input_a = Cpt(EpicsSignal, '.INPA')
    input_b = Cpt(EpicsSignal, '.INPB')
    input_c = Cpt(EpicsSignal, '.INPC')
    input_d = Cpt(EpicsSignal, '.INPD')
    input_e = Cpt(EpicsSignal, '.INPE')
    input_f = Cpt(EpicsSignal, '.INPF')
    input_g = Cpt(EpicsSignal, '.INPG')
    input_h = Cpt(EpicsSignal, '.INPH')
    input_i = Cpt(EpicsSignal, '.INPI')
    input_j = Cpt(EpicsSignal, '.INPJ')
    input_k = Cpt(EpicsSignal, '.INPK')
    input_l = Cpt(EpicsSignal, '.INPL')
